#!/usr/bin/env ruby

require 'open-uri'
require 'json'
open('http://api.wunderground.com/api/20c6230249f86710/geolookup/conditions/q/CA/San_Francisco.json') do |f|
  json_string = f.read
  parsed_json = JSON.parse(json_string)
  location = parsed_json['location']['city']
  temp_f = parsed_json['current_observation']['temp_f']
  puts "Current temperature in #{location} is: #{temp_f}\n"
end